# E-commerce Sales Analysis

This notebook analyzes an e-commerce sales dataset using Python and Pandas.
It explores sales based on categories, cities, products, and payment methods,
along with filtering, sorting, grouping, and aggregation operations.

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")

df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [35]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Shape: (100, 13)

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

Data Types:
Order_ID              int64
Order_Date           object
Customer             object
City                 object
Region               object
Category             object
Product              object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
Rating              float64
Payment_Method       object
dtype: object

## 2. Basic Sales Statistics

In [36]:
total_sales = df["Total_Sales"].sum()

print("Total Sales:", total_sales)

Total Sales: 447262.95000000007

In [37]:
average_sales = df["Total_Sales"].mean()

print("Average Sales per Order:", average_sales)

Average Sales per Order: 4472.629500000001

In [38]:
highest_sales = df["Total_Sales"].max()
lowest_sales = df["Total_Sales"].min()

print("Highest Sale:", highest_sales)
print("Lowest Sale:", lowest_sales)

Highest Sale: 13995.0
Lowest Sale: 449.1

In [39]:
total_quantity = df["Quantity"].sum()

print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 294

In [40]:
number_of_orders = df["Order_ID"].count()

print("Number of Orders:", number_of_orders)

Number of Orders: 100

In [41]:
print("Number of Orders:", df["Order_ID"].count())
print("Total Quantity Sold:", df["Quantity"].sum())
print("Total Sales:", df["Total_Sales"].sum())
print("Average Sales per Order:", df["Total_Sales"].mean())
print("Highest Sale:", df["Total_Sales"].max())
print("Lowest Sale:", df["Total_Sales"].min())

Number of Orders: 100
Total Quantity Sold: 294
Total Sales: 447262.95000000007
Average Sales per Order: 4472.629500000001
Highest Sale: 13995.0
Lowest Sale: 449.1

## 3. Filtering and Sorting

In [42]:
high_value_orders = df[df["Total_Sales"] > 5000]

print("Orders with sales greater than ₹5,000:")
display(high_value_orders)

Orders with sales greater than ₹5,000:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
7,1008,2026-04-27,Aman Kumar,Jammu,North,Clothing,Hoodie,4,1599,5,6076.20,4.3,Credit Card
9,1010,2026-03-11,Aman Kumar,Kochi,South,Clothing,Jacket,4,2499,10,8996.40,4.7,Credit Card
10,1011,2026-03-22,Rahul Das,Hyderabad,South,Home & Kitchen,Coffee Maker,2,3499,0,6998.00,4.2,UPI
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
16,1017,2026-03-17,Sana Malik,Hyderabad,South,Sports,Cricket Bat,3,2499,0,7497.00,4.0,Net Banking
18,1019,2026-05-19,Reyansh Jain,Chennai,South,Clothing,Jacket,3,2499,0,7497.00,4.7,UPI
27,1028,2026-04-19,Sana Malik,Chandigarh,North,Electronics,Wireless Headphones,4,1499,5,5696.20,4.6,UPI
28,1029,2026-01-28,Sara Ahmed,Hyderabad,South,Electronics,Wireless Headphones,4,1499,5,5696.20,4.1,Credit Card
32,1033,2026-06-28,Maryam Khan,Pune,West,Home & Kitchen,Mixer Grinder,3,2999,10,8097.30,4.7,Net Banking
37,1038,2026-03-08,Aditya Verma,Pune,West,Sports,Dumbbell Set,5,1999,5,9495.25,5.0,Debit Card
38,1039,2026-04-28,Vivaan Kapoor,Chandigarh,North,Home & Kitchen,Mixer Grinder,2,2999,5,5698.10,3.8,UPI
40,1041,2026-03-14,Ishita Gupta,Delhi,North,Home & Kitchen,Coffee Maker,2,3499,5,6648.10,4.6,Cash on Delivery
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
50,1051,2026-04-28,Aisha Mir,Bhubaneswar,East,Electronics,Smart Watch,2,3299,0,6598.00,4.2,Credit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
56,1057,2026-03-21,Alina Shah,Chennai,South,Home & Kitchen,Coffee Maker,3,3499,15,8922.45,4.5,Debit Card
58,1059,2026-01-01,Mehak Bhat,Chennai,South,Sports,Cricket Bat,4,2499,15,8496.60,4.2,Credit Card
59,1060,2026-04-24,Karan Joshi,Pune,West,Sports,Dumbbell Set,3,1999,10,5397.30,5.0,Credit Card
61,1062,2026-02-20,Kabir Ali,Mumbai,West,Electronics,Mechanical Keyboard,3,2499,0,7497.00,3.5,UPI
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
75,1076,2026-04-29,Ishita Gupta,Chennai,South,Electronics,Wireless Headphones,4,1499,0,5996.00,3.5,Debit Card
76,1077,2026-03-28,Reyansh Jain,Pune,West,Home & Kitchen,Electric Kettle,4,1499,5,5696.20,4.5,Debit Card
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
80,1081,2026-01-30,Reyansh Jain,Kolkata,East,Home & Kitchen,Electric Kettle,5,1499,15,6370.75,4.0,Debit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
92,1093,2026-05-16,Aisha Mir,Hyderabad,South,Sports,Cricket Bat,4,2499,15,8496.60,4.5,Cash on Delivery
93,1094,2026-03-06,Sara Ahmed,Mumbai,West,Home & Kitchen,Mixer Grinder,3,2999,5,8547.15,3.8,Credit Card
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking

In [43]:
sorted_sales = df.sort_values("Total_Sales", ascending=False)

print("Orders sorted by Total Sales:")
display(sorted_sales[["Order_ID", "Customer", "Product", "Total_Sales"]].head(10))

Orders sorted by Total Sales:

    Order_ID      Customer              Product  Total_Sales
48      1049  Ishita Gupta        Running Shoes     13995.00
52      1053  Ananya Singh        Running Shoes     13295.25
84      1085    Sana Malik         Coffee Maker     12596.40
89      1090  Aditya Verma          Cricket Bat     12495.00
12      1013   Maryam Khan               Jacket     10620.75
47      1048    Sara Ahmed         Coffee Maker     10497.00
69      1070  Aditya Verma               Jacket      9996.00
79      1080  Aditya Verma               Jacket      9996.00
51      1052   Rohan Mehta  Mechanical Keyboard      9496.20
3       1004     Kabir Ali  Mechanical Keyboard      9496.20

In [44]:
highest_order = df.loc[df["Total_Sales"].idxmax()]

print("Highest-Selling Order:")
display(highest_order)

Highest-Selling Order:

Order_ID                     1049
Order_Date             2026-03-02
Customer             Ishita Gupta
City                       Mumbai
Region                       West
Category                   Sports
Product             Running Shoes
Quantity                        5
Unit_Price                   2799
Discount_Percent                0
Total_Sales               13995.0
Rating                        4.0
Payment_Method        Net Banking
Name: 48, dtype: object

In [45]:
low_value_orders = df[df["Total_Sales"] < 2000]

print("Orders with sales below ₹2,000:")
display(low_value_orders)

Orders with sales below ₹2,000:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
5,1006,2026-01-21,Manya Rao,Kochi,South,Books,The Alchemist,1,499,10,449.10,4.2,Cash on Delivery
6,1007,2026-01-12,Alina Shah,Jaipur,North,Home & Kitchen,Water Bottle,2,699,0,1398.00,4.1,Debit Card
15,1016,2026-03-06,Manya Rao,Pune,West,Books,The Alchemist,4,499,15,1696.60,3.5,UPI
17,1018,2026-01-28,Aman Kumar,Srinagar,North,Home & Kitchen,Water Bottle,2,699,15,1188.30,4.2,Cash on Delivery
20,1021,2026-01-18,Reyansh Jain,Chandigarh,North,Sports,Yoga Mat,1,899,10,809.10,4.7,Credit Card
21,1022,2026-05-16,Priya Menon,Delhi,North,Books,The Alchemist,2,499,5,948.10,4.5,Credit Card
30,1031,2026-01-04,Rohan Mehta,Ahmedabad,West,Sports,Yoga Mat,1,899,15,764.15,4.1,Credit Card
31,1032,2026-01-16,Ishita Gupta,Pune,West,Books,Atomic Habits,2,599,10,1078.20,4.5,UPI
33,1034,2026-05-29,Maryam Khan,Delhi,North,Clothing,T-Shirt,2,799,0,1598.00,4.7,UPI
35,1036,2026-06-02,Rohan Mehta,Srinagar,North,Sports,Yoga Mat,2,899,0,1798.00,5.0,Credit Card
39,1040,2026-05-18,Aditya Verma,Ahmedabad,West,Sports,Dumbbell Set,1,1999,0,1999.00,4.7,Debit Card
42,1043,2026-05-22,Kabir Ali,Jaipur,North,Clothing,T-Shirt,1,799,0,799.00,4.2,Debit Card
43,1044,2026-05-10,Hiba Sheikh,Chennai,South,Clothing,T-Shirt,2,799,5,1518.10,4.2,UPI
44,1045,2026-03-27,Reyansh Jain,Jammu,North,Books,Machine Learning Basics,1,999,0,999.00,4.0,Debit Card
45,1046,2026-01-03,Ananya Singh,Delhi,North,Books,The Alchemist,4,499,15,1696.60,3.8,Credit Card
57,1058,2026-04-18,Alina Shah,Pune,West,Home & Kitchen,Water Bottle,2,699,0,1398.00,4.5,Credit Card
60,1061,2026-05-12,Alina Shah,Bengaluru,South,Books,Python Programming,1,749,5,711.55,5.0,Cash on Delivery
62,1063,2026-04-17,Aman Kumar,Chandigarh,North,Books,The Alchemist,1,499,10,449.10,4.8,Credit Card
64,1065,2026-04-29,Zoya Khan,Kolkata,East,Books,Python Programming,2,749,15,1273.30,4.7,Credit Card
68,1069,2026-03-27,Vivaan Kapoor,Ahmedabad,West,Electronics,Wireless Mouse,2,899,5,1708.10,4.7,UPI
73,1074,2026-03-28,Alina Shah,Lucknow,North,Books,Atomic Habits,1,599,10,539.10,5.0,Net Banking
77,1078,2026-01-05,Maryam Khan,Kolkata,East,Books,Machine Learning Basics,1,999,10,899.10,4.7,UPI
78,1079,2026-03-05,Aditya Verma,Mumbai,West,Clothing,Hoodie,1,1599,0,1599.00,3.5,Cash on Delivery
82,1083,2026-06-25,Priya Menon,Jammu,North,Sports,Football,1,799,5,759.05,3.8,Cash on Delivery
88,1089,2026-02-24,Aisha Mir,Srinagar,North,Books,Machine Learning Basics,2,999,10,1798.20,4.2,Debit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI

In [46]:
quantity_sorted = df.sort_values("Quantity", ascending=False)

print("Orders with the highest quantities:")
display(
    quantity_sorted[
        ["Order_ID", "Product", "Quantity", "Total_Sales"]
    ].head(10)
)

Orders with the highest quantities:

    Order_ID                Product  Quantity  Total_Sales
26      1027               Football         5      3395.75
24      1025               Football         5      3995.00
12      1013                 Jacket         5     10620.75
37      1038           Dumbbell Set         5      9495.25
71      1072               Yoga Mat         5      4045.50
72      1073          Atomic Habits         5      2545.75
80      1081        Electric Kettle         5      6370.75
83      1084         Wireless Mouse         5      4045.50
95      1096           Dumbbell Set         5      9495.25
99      1100  Data Science Handbook         5      4495.00

## 4. Grouping and Aggregation

In [47]:
category_sales = (
    df.groupby("Category")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Sales by Category:")
display(category_sales)

Total Sales by Category:

Category
Sports            136026.45
Home & Kitchen    113329.90
Electronics        92086.00
Clothing           69028.20
Books              36792.40
Name: Total_Sales, dtype: float64

In [48]:
category_quantity = (
    df.groupby("Category")["Quantity"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Quantity Sold by Category:")
display(category_quantity)

Total Quantity Sold by Category:

Category
Sports            79
Books             60
Home & Kitchen    59
Electronics       57
Clothing          39
Name: Quantity, dtype: int64

In [49]:
city_sales = (
    df.groupby("City")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Sales by City:")
display(city_sales)

Total Sales by City:

City
Hyderabad      59076.45
Chennai        47493.20
Lucknow        46194.65
Pune           41908.55
Mumbai         41457.80
Kochi          37257.50
Chandigarh     34539.65
Delhi          30882.80
Jaipur         25534.00
Kolkata        20169.00
Jammu          16059.75
Ahmedabad      14788.70
Bengaluru      13524.30
Srinagar       11778.60
Bhubaneswar     6598.00
Name: Total_Sales, dtype: float64

In [50]:
print("Top 10 Cities by Sales:")
display(city_sales.head(10))

Top 10 Cities by Sales:

City
Hyderabad     59076.45
Chennai       47493.20
Lucknow       46194.65
Pune          41908.55
Mumbai        41457.80
Kochi         37257.50
Chandigarh    34539.65
Delhi         30882.80
Jaipur        25534.00
Kolkata       20169.00
Name: Total_Sales, dtype: float64

In [51]:
product_sales = (
    df.groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Sales by Product:")
display(product_sales)

Total Sales by Product:

Product
Coffee Maker               51610.25
Jacket                     47106.15
Cricket Bat                41483.40
Running Shoes              41285.25
Wireless Headphones        33877.40
Dumbbell Set               30184.90
Mechanical Keyboard        26489.40
Electric Kettle            26382.40
Mixer Grinder              25341.55
Smart Watch                15670.25
Yoga Mat                   12765.80
Atomic Habits              11590.65
Football                   10307.10
Water Bottle                9995.70
Wireless Mouse              9574.35
T-Shirt                     7790.25
Hoodie                      7675.20
Python Programming          7527.45
The Alchemist               7485.00
Power Bank                  6474.60
Jeans                       6456.60
Machine Learning Basics     5694.30
Data Science Handbook       4495.00
Name: Total_Sales, dtype: float64

In [52]:
print("Top 10 Products by Sales:")
display(product_sales.head(10))

Top 10 Products by Sales:

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Dumbbell Set           30184.90
Mechanical Keyboard    26489.40
Electric Kettle        26382.40
Mixer Grinder          25341.55
Smart Watch            15670.25
Name: Total_Sales, dtype: float64

In [53]:
payment_sales = (
    df.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Total Sales by Payment Method:")
display(payment_sales)

Total Sales by Payment Method:

Payment_Method
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Cash on Delivery     50123.30
Name: Total_Sales, dtype: float64

In [54]:
category_summary = df.groupby("Category").agg(
    Total_Sales=("Total_Sales", "sum"),
    Average_Sales=("Total_Sales", "mean"),
    Total_Quantity=("Quantity", "sum"),
    Average_Rating=("Rating", "mean")
).sort_values("Total_Sales", ascending=False)

print("Category Summary:")
display(category_summary)

Category Summary:

                Total_Sales  Average_Sales  Total_Quantity  Average_Rating
Category
Sports            136026.45    5441.058000              79        4.400000
Home & Kitchen    113329.90    5396.661905              59        4.300000
Electronics        92086.00    4846.631579              57        4.236842
Clothing           69028.20    4930.585714              39        4.292857
Books              36792.40    1752.019048              60        4.347619

## 5. Identifying Top-Performing Categories and Products

In [55]:
top_category = category_sales.idxmax()
top_category_sales = category_sales.max()

print("Top-Performing Category:", top_category)
print("Total Sales:", top_category_sales)

Top-Performing Category: Sports
Total Sales: 136026.45

In [56]:
lowest_category = category_sales.idxmin()
lowest_category_sales = category_sales.min()

print("Lowest-Performing Category:", lowest_category)
print("Total Sales:", lowest_category_sales)

Lowest-Performing Category: Books
Total Sales: 36792.4

In [57]:
print("Top 5 Products by Total Sales:")
display(product_sales.head(5))

Top 5 Products by Total Sales:

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Name: Total_Sales, dtype: float64

In [58]:
print("Lowest 5 Products by Total Sales:")
display(product_sales.tail(5).sort_values())

Lowest 5 Products by Total Sales:

Product
Data Science Handbook      4495.0
Machine Learning Basics    5694.3
Jeans                      6456.6
Power Bank                 6474.6
The Alchemist              7485.0
Name: Total_Sales, dtype: float64

In [59]:
top_city = city_sales.idxmax()
top_city_sales = city_sales.max()

print("Top-Performing City:", top_city)
print("Total Sales:", top_city_sales)

Top-Performing City: Hyderabad
Total Sales: 59076.45

In [60]:
top_payment = payment_sales.idxmax()
top_payment_sales = payment_sales.max()

print("Payment Method with Highest Sales:", top_payment)
print("Total Sales:", top_payment_sales)

Payment Method with Highest Sales: Credit Card
Total Sales: 106540.25

In [61]:
sports_products = df[df["Category"] == "Sports"]

print("Sports Category Orders:")
display(
    sports_products[
        ["Order_ID", "Product", "Quantity", "Total_Sales"]
    ]
)

Sports Category Orders:

    Order_ID        Product  Quantity  Total_Sales
1       1002  Running Shoes         1      2799.00
11      1012    Cricket Bat         2      4498.20
13      1014  Running Shoes         3      8397.00
16      1017    Cricket Bat         3      7497.00
20      1021       Yoga Mat         1       809.10
22      1023       Football         3      2157.30
23      1024  Running Shoes         1      2799.00
24      1025       Football         5      3995.00
26      1027       Football         5      3395.75
30      1031       Yoga Mat         1       764.15
35      1036       Yoga Mat         2      1798.00
37      1038   Dumbbell Set         5      9495.25
39      1040   Dumbbell Set         1      1999.00
48      1049  Running Shoes         5     13995.00
52      1053  Running Shoes         5     13295.25
54      1055       Yoga Mat         4      3056.60
55      1056   Dumbbell Set         2      3798.10
58      1059    Cricket Bat         4      8496.60
59      1060   Dumbbell Set         3      5397.30
71      1072       Yoga Mat         5      4045.50
81      1082       Yoga Mat         3      2292.45
82      1083       Football         1       759.05
89      1090    Cricket Bat         5     12495.00
92      1093    Cricket Bat         4      8496.60
95      1096   Dumbbell Set         5      9495.25

In [62]:
high_rated = df[df["Rating"] >= 4.5]

print("Orders with Rating 4.5 or Higher:")
display(
    high_rated[
        ["Order_ID", "Product", "Category", "Rating", "Total_Sales"]
    ]
)

Orders with Rating 4.5 or Higher:

    Order_ID                  Product        Category  Rating  Total_Sales
2       1003               Power Bank     Electronics     4.6      2038.30
9       1010                   Jacket        Clothing     4.7      8996.40
11      1012              Cricket Bat          Sports     4.6      4498.20
12      1013                   Jacket        Clothing     4.8     10620.75
13      1014            Running Shoes          Sports     4.6      8397.00
14      1015      Wireless Headphones     Electronics     4.8      2998.00
18      1019                   Jacket        Clothing     4.7      7497.00
20      1021                 Yoga Mat          Sports     4.7       809.10
21      1022            The Alchemist           Books     4.5       948.10
24      1025                 Football          Sports     5.0      3995.00
26      1027                 Football          Sports     4.6      3395.75
27      1028      Wireless Headphones     Electronics     4.6      5696.20
31      1032            Atomic Habits           Books     4.5      1078.20
32      1033            Mixer Grinder  Home & Kitchen     4.7      8097.30
33      1034                  T-Shirt        Clothing     4.7      1598.00
34      1035             Coffee Maker  Home & Kitchen     4.7      2974.15
35      1036                 Yoga Mat          Sports     5.0      1798.00
36      1037               Power Bank     Electronics     4.8      2038.30
37      1038             Dumbbell Set          Sports     5.0      9495.25
39      1040             Dumbbell Set          Sports     4.7      1999.00
40      1041             Coffee Maker  Home & Kitchen     4.6      6648.10
47      1048             Coffee Maker  Home & Kitchen     5.0     10497.00
55      1056             Dumbbell Set          Sports     5.0      3798.10
56      1057             Coffee Maker  Home & Kitchen     4.5      8922.45
57      1058             Water Bottle  Home & Kitchen     4.5      1398.00
59      1060             Dumbbell Set          Sports     5.0      5397.30
60      1061       Python Programming           Books     5.0       711.55
62      1063            The Alchemist           Books     4.8       449.10
64      1065       Python Programming           Books     4.7      1273.30
65      1066              Smart Watch     Electronics     4.7      5938.20
68      1069           Wireless Mouse     Electronics     4.7      1708.10
70      1071             Water Bottle  Home & Kitchen     4.5      2516.40
72      1073            Atomic Habits           Books     4.6      2545.75
73      1074            Atomic Habits           Books     5.0       539.10
74      1075                    Jeans        Clothing     4.5      3228.30
76      1077          Electric Kettle  Home & Kitchen     4.5      5696.20
77      1078  Machine Learning Basics           Books     4.7       899.10
79      1080                   Jacket        Clothing     4.6      9996.00
81      1082                 Yoga Mat          Sports     4.5      2292.45
85      1086                    Jeans        Clothing     4.8      3228.30
87      1088       Python Programming           Books     4.5      2546.60
90      1091            Atomic Habits           Books     5.0      2995.00
92      1093              Cricket Bat          Sports     4.5      8496.60
94      1095               Power Bank     Electronics     4.6      2398.00
99      1100    Data Science Handbook           Books     4.8      4495.00

## 6. Key Observations

In [63]:
print(f"1. The top-performing category by total sales is {top_category}.")
print(f"   Total sales: {top_category_sales:.2f}")

print(f"\n2. The lowest-performing category by total sales is {lowest_category}.")
print(f"   Total sales: {lowest_category_sales:.2f}")

print(f"\n3. The top-performing city is {top_city}.")
print(f"   Total sales: {top_city_sales:.2f}")

print(f"\n4. The payment method generating the highest sales is {top_payment}.")
print(f"   Total sales: {top_payment_sales:.2f}")

print("\n5. The top 5 products by total sales are:")
display(product_sales.head(5))

1. The top-performing category by total sales is Sports.
   Total sales: 136026.45

2. The lowest-performing category by total sales is Books.
   Total sales: 36792.40

3. The top-performing city is Hyderabad.
   Total sales: 59076.45

4. The payment method generating the highest sales is Credit Card.
   Total sales: 106540.25

5. The top 5 products by total sales are:

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Name: Total_Sales, dtype: float64

## Conclusion

The e-commerce dataset was analyzed using Pandas to understand sales
performance across different categories, cities, products, and payment
methods. The analysis used filtering, sorting, grouping, and aggregation
to identify high-value orders and top-performing areas.

The results provide an overview of sales patterns and can help identify
strong-performing categories, products, cities, and payment methods.