In [1]:
import os
print(os.listdir())

['.config', 'Day9_Products.csv', 'Day9_Orders.csv', 'Day9_Customers.csv', 'sample_data']

In [2]:
import pandas as pd

orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

print("Orders:")
display(orders.head())

print("\nCustomers:")
display(customers.head())

print("\nProducts:")
display(products.head())

Orders:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Customers:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Products:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [3]:
print("Orders columns:")
print(orders.columns.tolist())

print("\nCustomers columns:")
print(customers.columns.tolist())

print("\nProducts columns:")
print(products.columns.tolist())

print("\nDataset shapes:")
print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Orders columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

Dataset shapes:
Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

## Merging Orders and Customers

In [4]:
orders_customers = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

print("Merged Orders + Customers:")
display(orders_customers.head())

Merged Orders + Customers:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

In [5]:
print("Merged dataset shape:", orders_customers.shape)
print("Merged dataset columns:")
print(orders_customers.columns.tolist())

Merged dataset shape: (120, 11)
Merged dataset columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type']

## Merging Products

In [6]:
processed_df = pd.merge(
    orders_customers,
    products,
    on="Product_ID",
    how="left"
)

print("Orders + Customers + Products:")
display(processed_df.head())

Orders + Customers + Products:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

In [7]:
print("Processed dataset shape:", processed_df.shape)

print("\nProcessed dataset columns:")
print(processed_df.columns.tolist())

Processed dataset shape: (120, 15)

Processed dataset columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

## Concatenating DataFrames

In [8]:
df_part1 = orders.head(5)
df_part2 = orders.tail(5)

print("First part:")
display(df_part1)

print("Second part:")
display(df_part2)

First part:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Second part:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [9]:
orders_combined = pd.concat(
    [df_part1, df_part2],
    ignore_index=True
)

print("Concatenated DataFrame:")
display(orders_combined)

Concatenated DataFrame:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
5,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
6,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
7,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
8,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
9,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [10]:
print("Original Orders rows:", len(orders))
print("Part 1 rows:", len(df_part1))
print("Part 2 rows:", len(df_part2))
print("Concatenated rows:", len(orders_combined))

Original Orders rows: 120
Part 1 rows: 5
Part 2 rows: 5
Concatenated rows: 10

## Creating a Derived Column Using apply()

In [11]:
print(processed_df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

In [12]:
def classify_quantity(quantity):
    if quantity >= 8:
        return "High"
    elif quantity >= 4:
        return "Medium"
    else:
        return "Low"

processed_df["Quantity_Category"] = processed_df["Quantity"].apply(classify_quantity)

display(
    processed_df[
        ["Order_ID", "Product_ID", "Quantity", "Quantity_Category"]
    ].head(10)
)

  Order_ID Product_ID  Quantity Quantity_Category
0    O0001       P019         2               Low
1    O0002       P003         2               Low
2    O0003       P004         1               Low
3    O0004       P015         3               Low
4    O0005       P009         5            Medium
5    O0006       P018         3               Low
6    O0007       P003         3               Low
7    O0008       P005         4            Medium
8    O0009       P009         2               Low
9    O0010       P005         2               Low

In [13]:
print("Quantity Category Distribution:")
display(processed_df["Quantity_Category"].value_counts())

Quantity Category Distribution:

Quantity_Category
Low       77
Medium    43
Name: count, dtype: int64

## Date and Time Processing

In [14]:
processed_df["Order_Date"] = pd.to_datetime(processed_df["Order_Date"])

print("Order_Date data type:")
print(processed_df["Order_Date"].dtype)

display(processed_df[["Order_ID", "Order_Date"]].head())

Order_Date data type:
datetime64[ns]

  Order_ID Order_Date
0    O0001 2026-02-19
1    O0002 2026-01-25
2    O0003 2026-02-26
3    O0004 2026-03-04
4    O0005 2026-03-29

In [15]:
processed_df["Order_Date"] = pd.to_datetime(processed_df["Order_Date"])

print("Order_Date data type:")
print(processed_df["Order_Date"].dtype)

display(processed_df[["Order_ID", "Order_Date"]].head())

Order_Date data type:
datetime64[ns]

  Order_ID Order_Date
0    O0001 2026-02-19
1    O0002 2026-01-25
2    O0003 2026-02-26
3    O0004 2026-03-04
4    O0005 2026-03-29

In [16]:
processed_df["Order_Day"] = processed_df["Order_Date"].dt.day

display(
    processed_df[
        ["Order_ID", "Order_Date", "Order_Day"]
    ].head(10)
)

  Order_ID Order_Date  Order_Day
0    O0001 2026-02-19         19
1    O0002 2026-01-25         25
2    O0003 2026-02-26         26
3    O0004 2026-03-04          4
4    O0005 2026-03-29         29
5    O0006 2026-02-09          9
6    O0007 2026-02-10         10
7    O0008 2026-03-27         27
8    O0009 2026-03-13         13
9    O0010 2026-03-05          5

In [17]:
processed_df["Order_DayOfWeek"] = processed_df["Order_Date"].dt.day_name()

display(
    processed_df[
        ["Order_ID", "Order_Date", "Order_DayOfWeek"]
    ].head(10)
)

  Order_ID Order_Date Order_DayOfWeek
0    O0001 2026-02-19        Thursday
1    O0002 2026-01-25          Sunday
2    O0003 2026-02-26        Thursday
3    O0004 2026-03-04       Wednesday
4    O0005 2026-03-29          Sunday
5    O0006 2026-02-09          Monday
6    O0007 2026-02-10         Tuesday
7    O0008 2026-03-27          Friday
8    O0009 2026-03-13          Friday
9    O0010 2026-03-05        Thursday

In [19]:
processed_df["Order_Month"] = processed_df["Order_Date"].dt.month

display(
    processed_df[
        ["Order_ID", "Order_Date", "Order_Month"]
    ].head(10)
)

  Order_ID Order_Date  Order_Month
0    O0001 2026-02-19            2
1    O0002 2026-01-25            1
2    O0003 2026-02-26            2
3    O0004 2026-03-04            3
4    O0005 2026-03-29            3
5    O0006 2026-02-09            2
6    O0007 2026-02-10            2
7    O0008 2026-03-27            3
8    O0009 2026-03-13            3
9    O0010 2026-03-05            3

In [20]:
display(
    processed_df[
        [
            "Order_ID",
            "Order_Date",
            "Order_Month",
            "Order_Day",
            "Order_DayOfWeek"
        ]
    ].head(10)
)

  Order_ID Order_Date  Order_Month  Order_Day Order_DayOfWeek
0    O0001 2026-02-19            2         19        Thursday
1    O0002 2026-01-25            1         25          Sunday
2    O0003 2026-02-26            2         26        Thursday
3    O0004 2026-03-04            3          4       Wednesday
4    O0005 2026-03-29            3         29          Sunday
5    O0006 2026-02-09            2          9          Monday
6    O0007 2026-02-10            2         10         Tuesday
7    O0008 2026-03-27            3         27          Friday
8    O0009 2026-03-13            3         13          Friday
9    O0010 2026-03-05            3          5        Thursday

## Final Data Cleaning and Inspection

In [21]:
print("Missing values in each column:")
display(processed_df.isnull().sum())

Missing values in each column:

Order_ID             0
Order_Date           0
Customer_ID          0
Product_ID           0
Quantity             0
Payment_Method       0
Order_Status         0
Customer_Name        0
City                 0
Region               0
Membership_Type      0
Product_Name         0
Category             0
Unit_Price           0
Brand                0
Quantity_Category    0
Order_Day            0
Order_DayOfWeek      0
Order_Month          0
dtype: int64

In [22]:
print("Rows before removing duplicates:", len(processed_df))

processed_df = processed_df.drop_duplicates()

print("Rows after removing duplicates:", len(processed_df))

Rows before removing duplicates: 120
Rows after removing duplicates: 120

In [23]:
print("Final dataset shape:", processed_df.shape)

print("\nFinal columns:")
print(processed_df.columns.tolist())

display(processed_df.head(10))

Final dataset shape: (120, 19)

Final columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status', 'Customer_Name', 'City', 'Region', 'Membership_Type', 'Product_Name', 'Category', 'Unit_Price', 'Brand', 'Quantity_Category', 'Order_Day', 'Order_DayOfWeek', 'Order_Month']

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Quantity_Category,Order_Day,Order_DayOfWeek,Order_Month
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,Low,19,Thursday,2
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,Low,25,Sunday,1
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,Low,26,Thursday,2
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,Low,4,Wednesday,3
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,Medium,29,Sunday,3
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone,Low,9,Monday,2
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear,Low,10,Tuesday,2
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus,Medium,27,Friday,3
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew,Low,13,Friday,3
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus,Low,5,Thursday,3

In [24]:
processed_df.to_csv(
    "Day9_Processed_Ecommerce.csv",
    index=False
)

print("Processed dataset exported successfully!")

Processed dataset exported successfully!

In [25]:
import os

print(os.listdir())

['.config', 'Day9_Processed_Ecommerce.csv', 'Day9_Products.csv', 'Day9_Orders.csv', 'Day9_Customers.csv', 'sample_data']